import Head from 'next/head';
import Feed from '../components/Feed';
import Sidebar from '../components/Sidebar';


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Sidebar />
        <Feed />
        {/**Widgets */}
        {/**Modal */}

      </main>


    </div>
  )
}

